FROM openjdk:8-jdk-alpine
ADD . /TechScreeningService
WORKDIR /TechScreeningService
ARG SCREENFORCE_CONFIG_SERVER_URL
ARG CALIBER_EUREKA_SERVER_URL
ENV SCREENFORCE_CONFIG_SERVER_URL $SCREENFORCE_CONFIG_SERVER_URL
ENV CALIBER_EUERKA_SERVER_URL $CALIBER_EUREKA_SERVER_URL
CMD ["java", "-jar", "target/tech-screening-service.jar"]
