/* screening service */
--------------------------------------------------------
--  CANDIDATE
--------------------------------------------------------
CREATE SEQUENCE    CANDIDATE_SEQUENCE  MINVALUE 1  INCREMENT BY 1 START WITH 4321;

INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (CANDIDATE_SEQUENCE.NEXTVAL, 'dschrute@mailinator.com','Schrute, Dwight','700-864-1234',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (CANDIDATE_SEQUENCE.NEXTVAL, 'jhalpert@mailinator.com','Halpert, Jim','700-864-2345',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'amartin@mailinator.com','Martin, Angela','700-864-4567',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'kmalone@mailinator.com','Malone, Kevin','700-864-5678',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'abernard@mailinator.com','Bernard, Andy','700-864-6789',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'gadams@mailinator.com','Adams, Gary','700-864-7890',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'elawrence@mailinator.com','Lawrence, Elaine','700-864-8901',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'qleyton@mailinator.com','Leyton, Quinn','700-864-9012',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'dcoke@mailinator.com','Coke, Donovan','700-864-0123',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'bparish@mailinator.com','Parish, Brian','700-865-1234',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'tbrewster@mailinator.com','Brewster, Tera','700-865-2345',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'gjohnson@mailinator.com','Johnson, Garrett','700-865-3456',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'kwood@mailinator.com','Wood, Kelly','700-865-4567',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'mrose@mailinator.com','Rose, Marissa','700-865-5678',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'lhex@mailinator.com','Hex, Leonard','700-865-6789',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'sgermanotta@mailinator.com','Germanotta, Stefani','700-865-7890',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'elawrence@mailinator.com','Lawrence, Elaine','700-864-8901',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'qleyton@mailinator.com','Leyton, Quinn','700-864-9012',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'dcoke@mailinator.com','Coke, Donovan','700-864-0123',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'bparish@mailinator.com','Parish, Brian','700-865-1234',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'tbrewster@mailinator.com','Brewster, Tera','700-865-2345',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'gjohnson@mailinator.com','Johnson, Garrett','700-865-3456',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'kwood@mailinator.com','Wood, Kelly','700-865-4567',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'mrose@mailinator.com','Rose, Marissa','700-865-5678',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL,'lhex@mailinator.com','Hex, Leonard','700-865-6789',null,null);
INSERT INTO CANDIDATE (CANDIDATE_ID,EMAIL,NAME,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (CANDIDATE_SEQUENCE.NEXTVAL, 'sgermanotta@mailinator.com','Germanotta, Stefani','700-865-7890',null,null);

--------------------------------------------------------
-- SCHEDULED_SCREENING
--------------------------------------------------------
CREATE SEQUENCE    SCHEDULED_SCREENING_SEQUENCE  MINVALUE 1  INCREMENT BY 1 START WITH 4321;

insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'SCREENED', (SYSDATE+13));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4325, 52, 'SCREENED', (SYSDATE+17));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'SCREENED', (SYSDATE+2));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4325, 52, 'PENDING', (SYSDATE+6));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4321, 52, 'SCREENED', (SYSDATE+35));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'PENDING', (SYSDATE+6));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4332, 52, 'PENDING', (SYSDATE+1));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4332, 52, 'PENDING', (SYSDATE+13));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4336, 51, 'SCREENED', (SYSDATE+4));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'PENDING', (SYSDATE+9));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4333, 52, 'SCREENED', (SYSDATE+12));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4333, 51, 'SCREENED', (SYSDATE+11));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4333, 52, 'PENDING', (SYSDATE+9));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4325, 51, 'PENDING', (SYSDATE+8));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4332, 51, 'PENDING', (SYSDATE+2));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4336, 52, 'PENDING', (SYSDATE+19));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'SCREENED', (SYSDATE+24));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4325, 52, 'SCREENED', (SYSDATE+20));
insert into SCHEDULED_SCREENING (SCHEDULED_SCREENING_ID, candidate_id, TRACK_ID, status, scheduled_date) values (SCHEDULED_SCREENING_SEQUENCE.NEXTVAL, 4326, 51, 'SCREENED', (SYSDATE+1));


--------------------------------------------------------
-- SCREENING
--------------------------------------------------------
CREATE SEQUENCE    SCREENING_SEQUENCE  MINVALUE 1  INCREMENT BY 1 START WITH 4321;

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 3, 51, 50.0, 'intoComment','generalComment','softskillComment', '2018-03-01', '2018-03-02', 0, 'Completed', 4321);
 
Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
 START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 3, 52, 50.0, 'intoComment2','generalComment2','softskillComment2', '2018-03-02', '2018-03-03', 0, 'Completed', 4322);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 4, 51, 50.0, 'intoComment3','generalComment3','softskillComment3', '2018-03-04', '2018-03-05', 0, 'Completed', 4323);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 5, 52, 50.0, 'intoComment4','generalComment4','softskillComment4', '2018-03-06', '2018-03-07', 0, 'Completed', 4324);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 5, 52, 50.0, 'intoComment5','generalComment5','softskillComment5', '2018-03-08', '2018-03-09', 1, 'Pending', 4325);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 5, 51, 50.0, 'intoComment6','generalComment6','softskillComment6', '2018-03-10', '2018-03-11', 1, 'Pending', 4326);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 3, 52, 50.0, 'intoComment7','generalComment7','softskillComment7', '2018-03-11', '2018-03-12', 0, 'Pending', 4327);

Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 3, 52, 50.0, 'intoComment8','generalComment8','softskillComment8', '2018-03-12', '2018-03-14', 1, 'Pending', 4328);
 
Insert into SCREENING (ID, SCREENER_ID, TRACK_ID,
COMPOSITE_SCORE, ABOUT_COMMENT, GENERAL_COMMENT, SOFT_SKILL_COMMENT,
START_DATE, END_DATE, SOFT_SKILL_VERDICT, STATUS, SCHEDULED_SCREENING_ID) 
values (SCREENING_SEQUENCE.NEXTVAL, 3, 51, 50.0, 'intoComment8','generalComment8','softskillComment8', '2018-03-12', '2018-03-14', 1, 'Pending', 4328);
 

--------------------------------------------------------
--  VIOLATION_TYPE
--------------------------------------------------------
CREATE SEQUENCE   VIOLATION_TYPE_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 4321;

Insert into VIOLATION_TYPE (VIOLATION_TYPE_ID, violation_type, DESCRIPTION)
values (VIOLATION_TYPE_SEQUENCE.NEXTVAL, 'Profanity', 'Expletives were used.');

Insert into VIOLATION_TYPE (VIOLATION_TYPE_ID, violation_type, DESCRIPTION)
values (VIOLATION_TYPE_SEQUENCE.NEXTVAL, 'Attire', 'Attire was not appropriate.');

Insert into VIOLATION_TYPE (VIOLATION_TYPE_ID, violation_type, DESCRIPTION)
values (VIOLATION_TYPE_SEQUENCE.NEXTVAL, 'Unfocused', 'Focus was not fully on the screening.');

--------------------------------------------------------
--  SOFT_SKILL_VIOLATION
--------------------------------------------------------
CREATE SEQUENCE   SOFT_SKILL_VIOLATION_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 4321;

Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4321, 4321, 'After failing a question, candidate started swearing.', '2018-03-01');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4322, 4321, 'Swore when yelling out to someone else behind him.', '2018-03-02');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4323, 4322, 'Was wearing pajamas', '2018-03-03');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4325, 4322, 'Wearing a graphic t-shirt.', '2018-03-04');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4326, 4323, 'Had many people in the same room. Was drinking.', '2018-03-05');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4327, 4323, 'He kept wandering off topic, was browsing a site.', '2018-03-06');
Insert into SOFT_SKILL_VIOLATION (SOFT_SKILL_VIOLATION_ID, SCREENING_ID, VIOLATION_TYPE_ID, COMMENT, TIME)
values (SOFT_SKILL_VIOLATION_SEQUENCE.NEXTVAL, 4328, 4323, 'Extremely distracted, was texting.', '2018-03-07');
 
COMMIT;


--------------------------------------------------------
--  QUESTION_SCORE
--------------------------------------------------------
CREATE SEQUENCE   QUESTION_SCORE_SEQUENCE MINVALUE 1 INCREMENT BY 1 START WITH 4321;

Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10010, 406, 4321, 3, 'Basic knowledge, average.', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10011, 407, 4321, 2, 'some understanding.', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10012, 404, 4321, 5, 'good', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10007, 410, 4321, 5, 'good', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10008, 411, 4321, 1, 'Bad wording, not sure they understand', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10009, 404, 4322, 3, 'Basic knowledge, average.', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10004, 412, 4322, 2, 'some understanding.', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10005, 410, 4322, 5, 'good', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10001, 413, 4322, 5, 'good', '2018-03-01');
Insert into QUESTION_SCORE (QUESTION_SCORE_ID, QUESTION_ID, CATEGORY_ID, SCREENING_ID, SCORE, COMMENT, TIME)
values (QUESTION_SCORE_SEQUENCE.NEXTVAL, 10002, 411, 4322, 1, 'Bad wording, not sure they understand', '2018-03-01');

COMMIT;